# PagesCMS Configuration
# https://pagescms.org

content:
  - name: settings
    label: "⚙️ Settings"
    path: content/settings.json
    type: file
    fields:
      - name: hostelName
        label: Hostel Name
        type: string
        required: true
      - name: logo
        label: Logo
        type: image
        options:
          path: public/images
      - name: primaryColor
        label: Primary Color
        type: string
        options:
          format: color
      - name: accentColor
        label: Accent Color
        type: string
        options:
          format: color
      - name: wifi
        label: WiFi
        type: object
        fields:
          - name: name
            label: Network Name
            type: string
          - name: password
            label: Password
            type: string
      - name: checkIn
        label: Check-in Time
        type: string
        description: "Format: HH:MM (e.g. 14:00)"
      - name: checkOut
        label: Check-out Time
        type: string
        description: "Format: HH:MM (e.g. 11:00)"
      - name: contactWhatsApp
        label: WhatsApp Number
        type: string
        description: "Include country code, e.g. +66812345678"
      - name: emergencyContacts
        label: Emergency Contacts
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
          - name: phone
            label: Phone
            type: string
      - name: timezone
        label: Timezone
        type: string
        description: "e.g. Asia/Bangkok"
      - name: heroImage
        label: Homepage Hero Image
        type: image
        options:
          path: public/images
        description: "Main background image on the homepage"
      - name: categoryImages
        label: Category Images
        type: object
        description: "Background images for explore cards on homepage"
        fields:
          - name: food
            label: Food & Drink
            type: image
            options:
              path: public/images
          - name: activities
            label: Activities
            type: image
            options:
              path: public/images
          - name: services
            label: Services
            type: image
            options:
              path: public/images
          - name: bars
            label: Bars & Nightlife
            type: image
            options:
              path: public/images

  - name: house-rules
    label: "📋 House Rules"
    path: content/house-rules.md
    type: file
    fields:
      - name: content
        label: Content
        type: rich-text

  - name: how-to-get-here
    label: "🗺️ How to Get Here"
    path: content/how-to-get-here.md
    type: file
    fields:
      - name: content
        label: Content
        type: rich-text

  - name: restaurants
    label: "🍜 Restaurants"
    path: content/spots/restaurants.json
    type: file
    fields:
      - name: spots
        label: Spots
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: tagline
            label: Tagline
            type: string
            description: "Short catchy description (e.g. 'Best pad thai in town 🍜')"
          - name: description
            label: Description
            type: text
          - name: cuisineType
            label: Cuisine Type
            type: select
            options:
              values:
                - thai
                - western
                - japanese
                - indian
                - chinese
                - vietnamese
                - italian
                - cafe
                - vegetarian
                - international
          - name: priceRange
            label: Price Range
            type: select
            options:
              values:
                - €
                - €€
                - €€€
          - name: address
            label: Address
            type: string
          - name: location
            label: Location
            type: object
            fields:
              - name: lat
                label: Latitude
                type: number
              - name: lng
                label: Longitude
                type: number
          - name: image
            label: Image
            type: image
            options:
              path: public/images/spots
          - name: phone
            label: Phone
            type: string
          - name: openingHours
            label: Opening Hours
            type: object
            description: "Default hours + exceptions per day"
            fields:
              - name: default
                label: Default Hours
                type: string
                description: "e.g. 11:30-22:00 (applies to all days)"
              - name: exceptions
                label: Exceptions
                type: object
                description: "Override for specific days"
                fields:
                  - name: monday
                    label: Monday
                    type: string
                    description: "Leave empty for default, 'closed' if closed"
                  - name: tuesday
                    label: Tuesday
                    type: string
                  - name: wednesday
                    label: Wednesday
                    type: string
                  - name: thursday
                    label: Thursday
                    type: string
                  - name: friday
                    label: Friday
                    type: string
                  - name: saturday
                    label: Saturday
                    type: string
                  - name: sunday
                    label: Sunday
                    type: string

  - name: bars
    label: "🍺 Bars"
    path: content/spots/bars.json
    type: file
    fields:
      - name: spots
        label: Spots
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: description
            label: Description
            type: text
          - name: priceRange
            label: Price Range
            type: select
            options:
              values:
                - €
                - €€
                - €€€
          - name: address
            label: Address
            type: string
          - name: location
            label: Location
            type: object
            fields:
              - name: lat
                label: Latitude
                type: number
              - name: lng
                label: Longitude
                type: number
          - name: image
            label: Image
            type: image
            options:
              path: public/images/spots
          - name: openingHours
            label: Opening Hours
            type: string

  - name: laundry
    label: "🧺 Laundry"
    path: content/spots/laundry.json
    type: file
    fields:
      - name: spots
        label: Spots
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: description
            label: Description
            type: text
          - name: priceRange
            label: Price Range
            type: select
            options:
              values:
                - €
                - €€
                - €€€
          - name: address
            label: Address
            type: string
          - name: location
            label: Location
            type: object
            fields:
              - name: lat
                label: Latitude
                type: number
              - name: lng
                label: Longitude
                type: number
          - name: image
            label: Image
            type: image
            options:
              path: public/images/spots
          - name: phone
            label: Phone
            type: string
          - name: openingHours
            label: Opening Hours
            type: string

  - name: transport
    label: "🛵 Transport"
    path: content/spots/transport.json
    type: file
    fields:
      - name: spots
        label: Spots
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: description
            label: Description
            type: text
          - name: priceRange
            label: Price Range
            type: select
            options:
              values:
                - €
                - €€
                - €€€
          - name: address
            label: Address
            type: string
          - name: location
            label: Location
            type: object
            fields:
              - name: lat
                label: Latitude
                type: number
              - name: lng
                label: Longitude
                type: number
          - name: image
            label: Image
            type: image
            options:
              path: public/images/spots
          - name: phone
            label: Phone
            type: string

  - name: activities
    label: "🎯 Activities"
    path: content/spots/activities.json
    type: file
    fields:
      - name: spots
        label: Spots
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: description
            label: Description
            type: text
          - name: priceRange
            label: Price Range
            type: select
            options:
              values:
                - €
                - €€
                - €€€
          - name: address
            label: Address
            type: string
          - name: location
            label: Location
            type: object
            fields:
              - name: lat
                label: Latitude
                type: number
              - name: lng
                label: Longitude
                type: number
          - name: image
            label: Image
            type: image
            options:
              path: public/images/spots
          - name: phone
            label: Phone
            type: string

  - name: events
    label: "📅 Events"
    path: content/events.json
    type: file
    fields:
      - name: events
        label: Events
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: tagline
            label: Tagline
            type: string
            description: "Short catchy description shown on cards"
          - name: description
            label: Description
            type: text
          - name: type
            label: Event Type
            type: select
            required: true
            options:
              values:
                - food
                - bars
                - activities
          - name: date
            label: Date
            type: date
            required: true
          - name: startTime
            label: Start Time
            type: string
            description: "Format: HH:MM (leave empty for All Day events)"
          - name: endTime
            label: End Time
            type: string
            description: "Format: HH:MM"
          - name: location
            label: Location
            type: string
            required: true
          - name: lat
            label: Latitude
            type: number
            description: "GPS latitude for Maps button"
          - name: lng
            label: Longitude
            type: number
            description: "GPS longitude for Maps button"
          - name: image
            label: Cover Image
            type: image
            options:
              path: public/images/events
            description: "Hero image for event detail page"
          - name: price
            label: Price
            type: string
            description: "e.g. Free, 500 THB, 1,200 THB"
          - name: cta
            label: Call to Action
            type: object
            description: "Button shown on event detail page"
            fields:
              - name: type
                label: Type
                type: select
                options:
                  values:
                    - whatsapp
                    - link
              - name: label
                label: Button Label
                type: string
                description: "e.g. Book Now, Join Us"
              - name: url
                label: URL / WhatsApp Number
                type: string
                description: "WhatsApp: +66812345678, Link: https://..."
              - name: message
                label: WhatsApp Message
                type: string
                description: "Pre-filled message for WhatsApp"

media:
  input: public/images
  output: public/images
